#!/usr/bin/env -S uv run --quiet python3
# /// script
# requires-python = ">=3.10"
# ///
"""Generate the fullwidth variant of the theme from the normal one.

Typora has no built-in width toggle and no theme-relative ``@import`` we can
rely on, so the theme ships as two theme files and the user picks one from
Typora's **Theme** menu:

    typora-vitepress.css             reading column (980px)  <- source of truth
    typora-vitepress-fullwidth.css   edge to edge (``none``) <- generated here

The two files differ by a single declaration; duplicating the 5 MB inlined
font payload by hand would be silly, so this script owns the transformation.
Never edit the generated file -- edit the base theme and re-run.

Usage
-----
    uv run tools/build-fullwidth.py            # regenerate the variant
    uv run tools/build-fullwidth.py --check    # fail if the variant is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# --- paths -----------------------------------------------------------------

ROOT = Path(__file__).resolve().parent.parent
BASE = ROOT / "typora-vitepress.css"
VARIANT = ROOT / "typora-vitepress-fullwidth.css"

# The one line that differs, whitespace included so the check is exact.
BASE_WIDTH = "  --write-max-width: 980px;"
FULL_WIDTH = "  --write-max-width: none;"

BANNER = """\
/*!
 * Typora VitePress Theme -- fullwidth variant
 *
 * GENERATED by tools/build-fullwidth.py from typora-vitepress.css.
 * Do not edit by hand: edit the base theme, then regenerate.
 */
"""


def generate(base: str) -> str:
    """Return the fullwidth theme built from the base theme source."""
    if base.count(BASE_WIDTH) != 1:
        sys.exit(
            f"{BASE.name}: expected exactly one {BASE_WIDTH.strip()!r} "
            f"(found {base.count(BASE_WIDTH)})"
        )
    return BANNER + "\n" + base.replace(BASE_WIDTH, FULL_WIDTH)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help=f"exit non-zero if {VARIANT.name} is out of date",
    )
    args = parser.parse_args()

    expected = generate(BASE.read_text())

    if args.check:
        actual = VARIANT.read_text() if VARIANT.exists() else None
        if actual != expected:
            sys.exit(f"{VARIANT.name} is stale -- run: uv run tools/build-fullwidth.py")
        print(f"{VARIANT.name} is up to date")
        return

    VARIANT.write_text(expected)
    print(f"  wrote   {VARIANT.name} ({len(expected) / 1e6:.2f} MB)")


if __name__ == "__main__":
    main()
